### PR TITLE
use built in perf.now

### PR DESCRIPTION
**Pull request by jimmywarting**

### CODE REVIEW

**Comment by CMTegner** [comment]
Hi. Thanks for the suggestion, but this is in fact [exactly what `performance-now` does](https://github.com/myrne/performance-now/blob/614099d729aef5d7bdbb85c0d1060166d63d05c7/src/performance-now.coffee#L1-L2) in environments that support the High Resolution Time API.

**Comment by jimmywarting** [comment]
just tough perf now was needed anymore b/c it exist everywhere now basically

**Comment by CMTegner** [comment]
The main intent of `raf` is to polyfill `requestAnimationFrame` in older browsers. If we only target newer browsers we would effectively be making this module redundant :·)

**Comment by jimmywarting** [comment]
> The main intent of `raf` is to polyfill `requestAnimationFrame` in older browsers. If we only target newer browsers we would effectively be making this module redundant :·)

it's pretty much impl everywhere now. IE11 has it and many have stop supporting older browser, heck even some have stop supporting IE11 also
so the only place that would need it is inside of NodeJS (and other worker threads)?

**Comment by ljharb** [comment]
I need raf to support older browsers than that, as do many others.

If you don’t need it, you can simply not depend on it, and alias it out in your bundler config or with package manager resolutions/overrides.

**Pull request closed without merging**
