### PR TITLE
Add raf.polyfill

### PR DESCRIPTION
**Pull request by caseyWebb**

### CODE REVIEW

**Comment by CMTegner** [comment]
Thanks! My only gripe with this change is that it doesn't polyfill `global` in a node environment. Perhaps `global = typeof window === 'undefined' ? {} : window` should be expanded to also check the actual `global` object (the variable will probably have to be renamed).

**Comment by ljharb** [comment]
I'm not sure what you mean - `global` will work in `node`, and browserify/webpack will make the same work in browsers.

**Comment by caseyWebb** [comment]
`global` is a local var here that hides node's `global`

**Comment by caseyWebb** [comment]
Looking at it now, I'm not even sure it's necessary. `requestAnimationFrame` looks like it should get attached to `window` w/o this PR... I might have just needed to go to bed.

**Comment by ljharb** [comment]
aha, that's a good point. We shouldn't have a local variable named "global".

**Comment by caseyWebb** [comment]
shabam :tada:

**Comment by CMTegner** [comment]
Good stuff! Published to npm as 3.2.0.

**Pull request merged**
